name: Build

on:
    push:
      branches:
      - "**"

      paths:
        - ".github/workflows/**"
        - "src/**"
        - "build.py"


    schedule:
      - cron: '30 8 * * *'
      - cron: '30 2 * * *'

jobs:
    zh_-CN:
        uses: ./.github/workflows/zh_CN.yml
    Release:
        runs-on: ubuntu-latest
        needs: Build
        if: ${{ needs.Build.outputs.release == 'true' }}
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4.2.1

          - name: Download Release Assets
            uses: actions/download-artifact@v4.1.8
            with:
              name: Release_${{ needs.Build.outputs.version }}
              path: build

          - name: Create Release Zip
            run: |
              cd build
              cp version ..
              zip -r ArknightsGameData.zip .

          - name: Commit Version
            uses: EndBug/add-and-commit@v9.1.4
            with:
              author_name: github-actions
              author_email: github-actions[bot]@users.noreply.github.com
              message: 'Commit from Github Action'
              add: 'version'
              tag_push: '--force'

          - name: Create Release
            uses: softprops/action-gh-release@v2.0.8
            with:
              files: build/ArknightsGameData.zip
              tag_name: ${{ needs.Build.outputs.version }}