name: Build

on:
    push:
      branches:
      - "**"

      paths:
        - ".github/workflows/**"
        - "src/**"
        - "build.py"

    schedule:
      - cron: '30 2 * * *'
      - cron: '30 8 * * *'
      - cron: '30 1 * * *'
      - cron: '30 7 * * *'
      - cron: '30 17 * * *'
      - cron: '30 23 * * *'

jobs:
    zh_CN:
        uses: ./.github/workflows/zh_CN.yml

    en_US:
        needs: [zh_CN]
        uses: ./.github/workflows/yostar.yml
        with:
          lang: en_US
          timezone: America/New_York
          timestamp: ${{ needs.zh_CN.outputs.timestamp }}

    ja_JP:
        needs: [zh_CN]
        uses: ./.github/workflows/yostar.yml
        with:
          lang: ja_JP
          timezone: Asia/Tokyo
          timestamp: ${{ needs.zh_CN.outputs.timestamp }}

    ko_KR:
        needs: [zh_CN]
        uses: ./.github/workflows/yostar.yml
        with:
          lang: ko_KR
          timezone: Asia/Seoul
          timestamp: ${{ needs.zh_CN.outputs.timestamp }}

    Release:
        needs: [zh_CN,en_US,ja_JP,ko_KR]
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4.2.1

        - name: Download Artifacts
          uses: actions/download-artifact@v4.1.8
          with:
            path: assets

        - name: Create Zip and Move Files
          run: |
            mkdir -p version && cd version
            mkdir -p zh_CN && mkdir -p en_US && mkdir -p ja_JP && mkdir -p ko_KR && cd ..

            cd assets
            cd zh_CN_${{ needs.zh_CN.outputs.timestamp }}
            zip -r -q zh_CN_${{ needs.zh_CN.outputs.timestamp }}.zip .
            mv zh_CN_${{ needs.zh_CN.outputs.timestamp }}.zip ..
            mv -f version ../../version/zh_CN/

            cd ../en_US_${{ needs.zh_CN.outputs.timestamp }}
            zip -r -q en_US_${{ needs.zh_CN.outputs.timestamp }}.zip .
            mv en_US_${{ needs.zh_CN.outputs.timestamp }}.zip ..
            mv -f version ../../version/en_US/

            cd ../ja_JP_${{ needs.zh_CN.outputs.timestamp }}
            zip -r -q ja_JP_${{ needs.zh_CN.outputs.timestamp }}.zip .
            mv ja_JP_${{ needs.zh_CN.outputs.timestamp }}.zip ..
            mv -f version ../../version/ja_JP/

            cd ../ko_KR_${{ needs.zh_CN.outputs.timestamp }}
            zip -r -q ko_KR_${{ needs.zh_CN.outputs.timestamp }}.zip .
            mv ko_KR_${{ needs.zh_CN.outputs.timestamp }}.zip ..
            mv -f version ../../version/ko_KR/

        - name: Commit zh_CN Version
          if: ${{ needs.zh_CN.outputs.release == 'true' }}
          uses: EndBug/add-and-commit@v9.1.4
          with:
            author_name: github-actions
            author_email: github-actions[bot]@users.noreply.github.com
            message: '[zh_CN] ${{ needs.zh_CN.outputs.ver }}'
            add: 'version/zh_CN/version'

        - name: Commit en_US Version
          if: ${{ needs.en_US.outputs.release == 'true' }}
          uses: EndBug/add-and-commit@v9.1.4
          with:
            author_name: github-actions
            author_email: github-actions[bot]@users.noreply.github.com
            message: '[en_US] ${{ needs.en_US.outputs.ver }}'
            add: 'version/en_US/version'

        - name: Commit ja_JP Version
          if: ${{ needs.ja_JP.outputs.release == 'true' }}
          uses: EndBug/add-and-commit@v9.1.4
          with:
            author_name: github-actions
            author_email: github-actions[bot]@users.noreply.github.com
            message: '[ja_JP] ${{ needs.ja_JP.outputs.ver }}'
            add: 'version/ja_JP/version'

        - name: Commit ko_KR Version
          if: ${{ needs.ko_KR.outputs.release == 'true' }}
          uses: EndBug/add-and-commit@v9.1.4
          with:
            author_name: github-actions
            author_email: github-actions[bot]@users.noreply.github.com
            message: '[ko_KR] ${{ needs.ko_KR.outputs.ver }}'
            add: 'version/ko_KR/version'

        - name: Create Release
          uses: softprops/action-gh-release@v2.1.0
          with:
            tag_name: ${{ needs.zh_CN.outputs.timestamp }}
            make_latest: true
            files: |
              assets/zh_CN_${{ needs.zh_CN.outputs.timestamp }}.zip
              assets/en_US_${{ needs.zh_CN.outputs.timestamp }}.zip
              assets/ja_JP_${{ needs.zh_CN.outputs.timestamp }}.zip
              assets/ko_KR_${{ needs.zh_CN.outputs.timestamp }}.zip
            body: |
             - zh_CN: ${{ needs.zh_CN.outputs.ver }}
             - en_US: ${{ needs.en_US.outputs.ver }}
             - ja_JP: ${{ needs.ja_JP.outputs.ver }}
             - ko_KR: ${{ needs.ko_KR.outputs.ver }}