name: Build

on:
    push:
      branches:
      - "**"

      paths:
        - ".github/workflows/**"
        - "src/**"
        - "build.py"


    schedule:
      - cron: '30 8 * * *'
      - cron: '30 2 * * *'

jobs:
    meta:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4.2.1

        - name: Setup Python
          uses: actions/setup-python@v5.2.0
          with:
            python-version: '3.12'

        - name: Run timestamp.py
          run: |
            python timestamp.py

        outputs:
          timestamp: ${{ env.TIMESTAMP }}

    zh_CN:
        needs: meta
        uses: ./.github/workflows/zh_CN.yml
        with:
          timestamp: ${{ needs.meta.outputs.timestamp }}

    Release:
        needs: [meta,zh_CN]
        runs-on: ubuntu-latest
        if: ${{ needs.zh_CN.outputs.release == 'true' }}
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4.2.1

        - name: Create Release
          uses: ncipollo/release-action@v1.14.0
          with:
            artifacts: zh_${{ needs.meta.outputs.timestamp }}
            tag: ${{ needs.meta.outputs.timestamp }}