name: Build

on:
    push:
      branches:
      - "**"

      paths:
        - ".github/workflows/**"
        - "src/**"
        - "version/**"
        - "build.py"

    schedule:
      - cron: '30 2 * * *'
      - cron: '30 8 * * *'
      - cron: '30 1 * * *'
      - cron: '30 7 * * *'
      - cron: '30 17 * * *'
      - cron: '30 23 * * *'

jobs:
    meta:
      runs-on: macos-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4.2.1

        - name: Setup Python
          uses: actions/setup-python@v5.2.0
          with:
            python-version: "3.12"
        - name: Run meta.py
          run: |
            python meta.py

      outputs:
        timestamp: ${{ env.timestamp }}
        enable_workflow: ${{ env.enable_workflow }}
        create_release: ${{ env.create_release }}
        zh_CN: ${{ env.zh_CN }}
        en_US: ${{ env.en_US }}
        ja_JP: ${{ env.ja_JP }}
        ko_KR: ${{ env.ko_KR }}

    zh_CN:
        needs: meta
        if: ${{ needs.meta.outputs.zh_CN == 'true' }}
        uses: ./.github/workflows/data.yml
        with:
          checkout_repo: yuanyan3060/ArknightsGameResource
          checkout_files: |
            avatar
            gamedata/excel/character_table.json
          checkout_path: cache/zh_CN
          lang: zh_CN
          timezone: Asia/Shanghai
          timestamp: ${{ needs.meta.outputs.timestamp }}

    en_US:
        needs: [meta,zh_CN]
        if: ${{ needs.meta.outputs.en_US == 'true' }}
        uses: ./.github/workflows/data.yml
        with:
          lang: en_US
          timezone: America/New_York
          timestamp: ${{ needs.zh_CN.outputs.timestamp }}

    ja_JP:
        needs: [meta,zh_CN]
        if: ${{ needs.meta.outputs.ja_JP == 'true' }}
        uses: ./.github/workflows/data.yml
        with:
          lang: ja_JP
          timezone: Asia/Tokyo
          timestamp: ${{ needs.zh_CN.outputs.timestamp }}

    ko_KR:
        needs: [meta,zh_CN]
        if: ${{ needs.meta.outputs.ko_KR == 'true' }}
        uses: ./.github/workflows/data.yml
        with:
          lang: ko_KR
          timezone: Asia/Seoul
          timestamp: ${{ needs.zh_CN.outputs.timestamp }}

    Release:
        needs: [meta,zh_CN,en_US,ja_JP,ko_KR]
        runs-on: macos-latest
        if: needs.meta.outputs.create_release == 'true' && (needs.zh_CN.outputs.release == 'true' || needs.en_US.outputs.release == 'true' || needs.ja_JP.outputs.release == 'true' || needs.ko_KR.outputs.release == 'true')
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4.2.1

        - name: Download Artifacts
          uses: actions/download-artifact@v4.1.8
          with:
            path: assets

        - name: Create Zip and Move Files
          run: |
            mkdir -p version && cd version
            mkdir -p zh_CN && mkdir -p en_US && mkdir -p ja_JP && mkdir -p ko_KR && cd ..

            cd assets
            cd zh_CN-${{ needs.zh_CN.outputs.timestamp }} && mv version-zh_CN ..
            zip -r -q zh_CN-${{ needs.zh_CN.outputs.timestamp }}.zip .
            mv zh_CN-${{ needs.zh_CN.outputs.timestamp }}.zip ..
            mv -f version ../../version/zh_CN/

            cd ../en_US-${{ needs.zh_CN.outputs.timestamp }} && mv version-en_US ..
            zip -r -q en_US-${{ needs.zh_CN.outputs.timestamp }}.zip .
            mv en_US-${{ needs.zh_CN.outputs.timestamp }}.zip ..
            mv -f version ../../version/en_US/

            cd ../ja_JP-${{ needs.zh_CN.outputs.timestamp }} && mv version-ja_JP ..
            zip -r -q ja_JP-${{ needs.zh_CN.outputs.timestamp }}.zip .
            mv ja_JP-${{ needs.zh_CN.outputs.timestamp }}.zip ..
            mv -f version ../../version/ja_JP/

            cd ../ko_KR-${{ needs.zh_CN.outputs.timestamp }} && mv version-ko_KR ..
            zip -r -q ko_KR-${{ needs.zh_CN.outputs.timestamp }}.zip .
            mv ko_KR-${{ needs.zh_CN.outputs.timestamp }}.zip ..
            mv -f version ../../version/ko_KR/

        - name: Commit zh_CN Version
          if: ${{ needs.zh_CN.outputs.release == 'true' }}
          uses: EndBug/add-and-commit@v9.1.4
          with:
            author_name: github-actions
            author_email: github-actions[bot]@users.noreply.github.com
            message: '[zh_CN] ${{ needs.zh_CN.outputs.ver }}'
            add: 'version/zh_CN/version'

        - name: Commit en_US Version
          if: ${{ needs.en_US.outputs.release == 'true' }}
          uses: EndBug/add-and-commit@v9.1.4
          with:
            author_name: github-actions
            author_email: github-actions[bot]@users.noreply.github.com
            message: '[en_US] ${{ needs.en_US.outputs.ver }}'
            add: 'version/en_US/version'

        - name: Commit ja_JP Version
          if: ${{ needs.ja_JP.outputs.release == 'true' }}
          uses: EndBug/add-and-commit@v9.1.4
          with:
            author_name: github-actions
            author_email: github-actions[bot]@users.noreply.github.com
            message: '[ja_JP] ${{ needs.ja_JP.outputs.ver }}'
            add: 'version/ja_JP/version'

        - name: Commit ko_KR Version
          if: ${{ needs.ko_KR.outputs.release == 'true' }}
          uses: EndBug/add-and-commit@v9.1.4
          with:
            author_name: github-actions
            author_email: github-actions[bot]@users.noreply.github.com
            message: '[ko_KR] ${{ needs.ko_KR.outputs.ver }}'
            add: 'version/ko_KR/version'

        - name: Create Release
          uses: softprops/action-gh-release@v2.1.0
          with:
            tag_name: ${{ needs.zh_CN.outputs.timestamp }}
            make_latest: true
            files: |
              assets/zh_CN-${{ needs.zh_CN.outputs.timestamp }}.zip
              assets/en_US-${{ needs.zh_CN.outputs.timestamp }}.zip
              assets/ja_JP-${{ needs.zh_CN.outputs.timestamp }}.zip
              assets/ko_KR-${{ needs.zh_CN.outputs.timestamp }}.zip
              assets/version-zh_CN
              assets/version-en_US
              assets/version-ja_JP
              assets/version-ko_KR
            body: |
             - zh_CN: ${{ needs.zh_CN.outputs.ver }}
             - en_US: ${{ needs.en_US.outputs.ver }}
             - ja_JP: ${{ needs.ja_JP.outputs.ver }}
             - ko_KR: ${{ needs.ko_KR.outputs.ver }}