name: Build

on:
    push:
      branches:
      - "**"

      paths:
        - ".github/workflows/**"
        - "src/**"
        - "build.py"


    schedule:
      - cron: '30 8 * * *'
      - cron: '30 2 * * *'

jobs:
    meta:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4.2.1

        - name: Setup Python
          uses: actions/setup-python@v5.2.0
          with:
            python-version: '3.12'

        - name: Run timestamp.py
          run: |
            python timestamp.py

        outputs:
          timestamp: ${{ env.TIMESTAMP }}

    zh_CN:
        needs: meta
        uses: ./.github/workflows/zh_CN.yml
        with:
          timestamp: ${{ needs.meta.outputs.timestamp }}

    en_US:
        needs: [meta,zh_CN]
        uses: ./.github/workflows/yostar.yml
        with:
          lang: en_US
          timezone: America/New_York
          timestamp: ${{ needs.meta.outputs.timestamp }}

    ja_JP:
        needs: [meta,zh_CN]
        uses: ./.github/workflows/yostar.yml
        with:
          lang: ja_JP
          timezone: Asia/Tokyo
          timestamp: ${{ needs.meta.outputs.timestamp }}

    ko_KR:
        needs: [meta,zh_CN]
        uses: ./.github/workflows/yostar.yml
        with:
          lang: ko_KR
          timezone: Asia/Seoul
          timestamp: ${{ needs.meta.outputs.timestamp }}

    Release:
        needs: [meta,zh_CN,en_US,ja_JP,ko_KR]
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4.2.1

        - name: Download Artifacts
          uses: actions/download-artifact@v4.1.8
          with:
            path: assets

        - name: Create Zip
          run: |
            cd assets
            zip -r -q zh_CN_${{ needs.meta.outputs.timestamp }}.zip zh_CN_${{ needs.meta.outputs.timestamp }}/*
            zip -r -q en_US_${{ needs.meta.outputs.timestamp }}.zip en_US_${{ needs.meta.outputs.timestamp }}/en_US_${{ needs.meta.outputs.timestamp }}/*
            zip -r -q ja_JP_${{ needs.meta.outputs.timestamp }}.zip ja_JP_${{ needs.meta.outputs.timestamp }}/ja_JP_${{ needs.meta.outputs.timestamp }}/*
            zip -r -q ko_KR_${{ needs.meta.outputs.timestamp }}.zip ko_KR_${{ needs.meta.outputs.timestamp }}/ko_KR_${{ needs.meta.outputs.timestamp }}/*

        - name: Create Release
          uses: softprops/action-gh-release@v2.1.0
          with:
            tag_name: ${{ needs.meta.outputs.timestamp }}
            make_latest: true
            files: |
              assets/zh_CN_${{ needs.meta.outputs.timestamp }}.zip
              assets/en_US_${{ needs.meta.outputs.timestamp }}.zip
              assets/ja_JP_${{ needs.meta.outputs.timestamp }}.zip
              assets/ko_KR_${{ needs.meta.outputs.timestamp }}.zip
