name: Yostar

on:
    workflow_call:
      inputs:
        lang:
          required: true
          type: string
        timezone:
          required: true
          type: string
        timestamp:
          required: true
          type: string
      outputs:
        release:
          value: ${{ jobs.Build.outputs.RELEASE }}
        ver:
          value: ${{ jobs.Build.outputs.ver }}

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4.2.1

        - name: Checkout ArknightsGameResource
          uses: actions/checkout@v4.2.1
          with:
            repository: Kengxxiao/ArknightsGameData_YoStar
            ref: main
            path: cache
            sparse-checkout: |
              ${{ inputs.lang }}/gamedata/excel/character_table.json

        - name: Set Timezone
          uses: szenius/set-timezone@v1.1
          with:
            timezoneLinux: ${{ inputs.timezone }}

        - name: Setup Python
          uses: actions/setup-python@v5.2.0
          with:
            python-version: '3.12'

        - name: Run build.py
          run: |
              pip install --upgrade pip
              pip install -r requirements.txt
              mkdir version/${{ inputs.lang }} -p
              python build.py ${{ inputs.lang }}

        - name: Download Avatar
          uses: actions/download-artifact@v4.1.8
          with:
            name: avatar_${{ inputs.timestamp }}
            path: build/avatar

        - name: Upload Release Artifact
          uses: actions/upload-artifact@v4.4.1
          with:
            name: ${{ inputs.lang }}_${{ inputs.timestamp }}
            path: |
              build/*

        - name: Commit Version
          if: ${{ env.RELEASE == 'true' }}
          uses: EndBug/add-and-commit@v9.1.4
          with:
            pull: '--rebase --all'
            author_name: github-actions
            author_email: github-actions[bot]@users.noreply.github.com
            message: '[${{ inputs.lang }}] ${{ env.VER }}'
            add: 'version/${{ inputs.lang }}/version'

        outputs:
          release: ${{ env.RELEASE }}
          ver: ${{ env.VER }}
