on:
    workflow_call:
      outputs:
        release:
          value: ${{ jobs.Build.outputs.RELEASE }}
jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4.2.1

        - name: Checkout ArknightsGameResource
          uses: actions/checkout@v4.2.1
          with:
            repository: yuanyan3060/ArknightsGameResource
            ref: main
            path: cache/zh_CN
            sparse-checkout: |
              avatar
              gamedata/excel/character_table.json
              version

        - name: Set Timezone
          uses: szenius/set-timezone@v1.1
          with:
            timezoneLinux: 'Asia/Shanghai'

        - name: Setup Python
          uses: actions/setup-python@v5.2.0
          with:
            python-version: '3.12'

        - name: Run build.py
          run: |
              pip install --upgrade pip
              pip install -r requirements.txt
              mkdir version/zh_CN -p
              python build.py zh_CN

        - name: Upload Release Assets
          uses: actions/upload-artifact@v4.4.1
          with:
            name: zh_CN_${{ inputs.time }}
            path: |
              build/*
              !build/character_table_full.json

        outputs:
          release: ${{ env.RELEASE }}
