name: zh_CN

on:
    workflow_call:
      outputs:
        timestamp:
          value: ${{ jobs.Build.outputs.timestamp }}
        release:
          value: ${{ jobs.Build.outputs.RELEASE }}

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4.2.1

        - name: Checkout ArknightsGameResource
          uses: actions/checkout@v4.2.1
          with:
            repository: yuanyan3060/ArknightsGameResource
            ref: main
            path: cache/zh_CN
            sparse-checkout: |
              avatar
              gamedata/excel/character_table.json
              version

        - name: Set Timezone
          uses: szenius/set-timezone@v1.1
          with:
            timezoneLinux: 'Asia/Shanghai'

        - name: Setup Python
          uses: actions/setup-python@v5.2.0
          with:
            python-version: '3.12'

        - name: Run build.py
          run: |
              pip install --upgrade pip
              pip install -r requirements.txt
              mkdir version/zh_CN -p
              python timestamp
              python build.py zh_CN

        - name: Upload Avatar Artifact
          uses: actions/upload-artifact@v4.4.1
          with:
            name: avatar_${{ env.TIMESTAMP }}
            path: |
              build/avatar/*

        - name: Upload Release Artifact
          uses: actions/upload-artifact@v4.4.1
          with:
            name: zh_CN_${{ env.TIMESTAMP }}
            path: |
              build/*

        - name: Commit Version
          if: ${{ env.release == 'true' }}
          uses: EndBug/add-and-commit@v9.1.4
          with:
            author_name: github-actions
            author_email: github-actions[bot]@users.noreply.github.com
            message: '[zh_CN] ${{ env.VER }}'
            add: 'version/zh_CN/version'
            tag_push: '--force'

        outputs:
          timestamp: ${{ env.TIMESTAMP }}
          release: ${{ env.RELEASE }}
          filename: zh_CN_${{ env.TIMESTAMP }}
